// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubssskafbrslctfmcytn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVic3Nza2FmYnJzbGN0Zm1jeXRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzU3MTEsImV4cCI6MjA2NjMxMTcxMX0.9WeG9lOiKU-JbplT-gVkd1WhfeXHwjphB6SLWBtSUWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);